# 29 — Evidence-gated source-only domain generalization

This notebook tests whether the established lower-back acceleration classifier can be improved without using either frozen external cohort for model selection. The development sources are Felius, Voisard, and Sint Maartenskliniek. RevalExo and NONAN remain unread.

## Predeclared comparison

1. **ERM control:** established Inception encoder, source/class-balanced batches, AdamW.
2. **Deep CORAL:** the same encoder and classifier plus the released mean-and-covariance alignment loss (weight 1.0).
3. **ERM++-style:** the same encoder with classifier warm-up, Adam weight decay, and simple moving-average evaluation. It is labelled *style* because an ImageNet-pretrained time-series encoder is unavailable.
4. **Secondary complementary-error audit:** after neither standalone candidate passed the first gate, deterministic equal-probability ensembles are evaluated from the matched out-of-source participant predictions. This rescue analysis is explicitly exploratory and uses development cohorts only.

The design follows the official [Deep CORAL implementation](https://github.com/VisionLearningGroup/CORAL), the official [ERM++ implementation](https://github.com/lovelyqian/ERMPlusPlus), and the HAROOD wearable domain-generalization benchmark. None establishes universal superiority, so this notebook requires empirical non-inferiority and a material gain.

## Leakage controls and decision rule

- Outer evaluation: leave one entire development source out.
- Inner tuning: participant-disjoint 20% validation inside the two training sources only.
- Epoch choice: 4/8/12/16 using worst-source balanced accuracy, then specificity, Brier score, and earlier stopping.
- Final repetitions: seeds 42, 137, 202, 314, and 515.
- Primary input: lower-back acceleration magnitude only, preserving the original research question.
- Candidate acceptance: predefined worst-source and paired-bootstrap non-inferiority bounds plus a material gain.
- Three-channel confirmation runs only if a standalone method or fixed ensemble passes the lower-back gate.

In [1]:
from pathlib import Path
import json, sys
import pandas as pd
import torch

ROOT = Path.cwd().resolve()
if ROOT.name == 'notebooks':
    ROOT = ROOT.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from src.models.evidence_gated_domain_generalization import BenchmarkConfig, run

assert torch.cuda.is_available(), 'GPU is required for this benchmark'
module_text = (ROOT / 'src/models/evidence_gated_domain_generalization.py').read_text(encoding='utf-8')
for forbidden in ('revalexo_external_windows', 'nonan_external_windows'):
    assert forbidden not in module_text.lower(), f'Frozen-cohort load reference found: {forbidden}'
print('Project:', ROOT)
print('GPU:', torch.cuda.get_device_name(0))
print('Frozen evaluation cohorts referenced by loader: NONE')

Project: C:\Users\frank\Documents\MR-ICT Review Paper
GPU: NVIDIA GeForce RTX 5060 Laptop GPU
Frozen evaluation cohorts referenced by loader: NONE

In [2]:
lower_back_config = BenchmarkConfig(representation='lower_back_acceleration')
lower_back = run(ROOT, lower_back_config)

Device: cuda | NVIDIA GeForce RTX 5060 Laptop GPU
Representation: lower_back_acceleration | channels=[0]
source                label
felius_2024           healthy     34
                      stroke     129
sint_maartenskliniek  healthy     20
                      stroke      10
voisard_2025          healthy     72
                      stroke      49
Name: participants, dtype: int64

C:\Users\frank\Documents\MR-ICT Review Paper\src\models\evidence_gated_domain_generalization.py:410: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  validation_history = history_frame.loc[history_frame.get("validation", False).fillna(False)].copy()

Tuned felius_2024 erm: 12 epochs

C:\Users\frank\Documents\MR-ICT Review Paper\src\models\evidence_gated_domain_generalization.py:410: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  validation_history = history_frame.loc[history_frame.get("validation", False).fillna(False)].copy()

Tuned felius_2024 coral: 16 epochs

C:\Users\frank\Documents\MR-ICT Review Paper\src\models\evidence_gated_domain_generalization.py:410: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  validation_history = history_frame.loc[history_frame.get("validation", False).fillna(False)].copy()

Tuned felius_2024 ermpp_style: 12 epochs

C:\Users\frank\Documents\MR-ICT Review Paper\src\models\evidence_gated_domain_generalization.py:410: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  validation_history = history_frame.loc[history_frame.get("validation", False).fillna(False)].copy()

Tuned sint_maartenskliniek erm: 8 epochs

C:\Users\frank\Documents\MR-ICT Review Paper\src\models\evidence_gated_domain_generalization.py:410: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  validation_history = history_frame.loc[history_frame.get("validation", False).fillna(False)].copy()

Tuned sint_maartenskliniek coral: 16 epochs

C:\Users\frank\Documents\MR-ICT Review Paper\src\models\evidence_gated_domain_generalization.py:410: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  validation_history = history_frame.loc[history_frame.get("validation", False).fillna(False)].copy()

Tuned sint_maartenskliniek ermpp_style: 8 epochs

C:\Users\frank\Documents\MR-ICT Review Paper\src\models\evidence_gated_domain_generalization.py:410: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  validation_history = history_frame.loc[history_frame.get("validation", False).fillna(False)].copy()

Tuned voisard_2025 erm: 4 epochs

C:\Users\frank\Documents\MR-ICT Review Paper\src\models\evidence_gated_domain_generalization.py:410: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  validation_history = history_frame.loc[history_frame.get("validation", False).fillna(False)].copy()

Tuned voisard_2025 coral: 4 epochs

C:\Users\frank\Documents\MR-ICT Review Paper\src\models\evidence_gated_domain_generalization.py:410: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  validation_history = history_frame.loc[history_frame.get("validation", False).fillna(False)].copy()

Tuned voisard_2025 ermpp_style: 8 epochs

Complete felius_2024 seed=42 method=erm

Complete felius_2024 seed=42 method=coral

Complete felius_2024 seed=42 method=ermpp_style

Complete felius_2024 seed=137 method=erm

Complete felius_2024 seed=137 method=coral

Complete felius_2024 seed=137 method=ermpp_style

Complete felius_2024 seed=202 method=erm

Complete felius_2024 seed=202 method=coral

Complete felius_2024 seed=202 method=ermpp_style

Complete felius_2024 seed=314 method=erm

Complete felius_2024 seed=314 method=coral

Complete felius_2024 seed=314 method=ermpp_style

Complete felius_2024 seed=515 method=erm

Complete felius_2024 seed=515 method=coral

Complete felius_2024 seed=515 method=ermpp_style

Complete sint_maartenskliniek seed=42 method=erm

Complete sint_maartenskliniek seed=42 method=coral

Complete sint_maartenskliniek seed=42 method=ermpp_style

Complete sint_maartenskliniek seed=137 method=erm

Complete sint_maartenskliniek seed=137 method=coral

Complete sint_maartenskliniek seed=137 method=ermpp_style

Complete sint_maartenskliniek seed=202 method=erm

Complete sint_maartenskliniek seed=202 method=coral

Complete sint_maartenskliniek seed=202 method=ermpp_style

Complete sint_maartenskliniek seed=314 method=erm

Complete sint_maartenskliniek seed=314 method=coral

Complete sint_maartenskliniek seed=314 method=ermpp_style

Complete sint_maartenskliniek seed=515 method=erm

Complete sint_maartenskliniek seed=515 method=coral

Complete sint_maartenskliniek seed=515 method=ermpp_style

Complete voisard_2025 seed=42 method=erm

Complete voisard_2025 seed=42 method=coral

Complete voisard_2025 seed=42 method=ermpp_style

Complete voisard_2025 seed=137 method=erm

Complete voisard_2025 seed=137 method=coral

Complete voisard_2025 seed=137 method=ermpp_style

Complete voisard_2025 seed=202 method=erm

Complete voisard_2025 seed=202 method=coral

Complete voisard_2025 seed=202 method=ermpp_style

Complete voisard_2025 seed=314 method=erm

Complete voisard_2025 seed=314 method=coral

Complete voisard_2025 seed=314 method=ermpp_style

Complete voisard_2025 seed=515 method=erm

Complete voisard_2025 seed=515 method=coral

Complete voisard_2025 seed=515 method=ermpp_style

            method      held_out_source  auroc  brier  balanced_accuracy  specificity  sensitivity  false_positives
             coral          felius_2024 0.8532 0.2047             0.7385       0.7824       0.6946              7.4
             coral sint_maartenskliniek 0.8970 0.1271             0.8050       0.8100       0.8000              3.8
             coral         voisard_2025 0.9243 0.1321             0.8319       0.7250       0.9388             19.8
      ensemble_all          felius_2024 0.8588 0.1551             0.7637       0.7647       0.7628              8.0
      ensemble_all sint_maartenskliniek 0.8950 0.1387             0.8400       0.8000       0.8800              4.0
      ensemble_all         voisard_2025 0.9108 0.1338             0.8384       0.7583       0.9184             17.4
ensemble_erm_coral          felius_2024 0.8556 0.1805             0.7459       0.7647       0.7271              8.0
ensemble_erm_coral sint_maartenskliniek 0.8950 0.1317             0.8250       0.8100       0.8400              3.8
ensemble_erm_coral         voisard_2025 0.9182 0.1495             0.8137       0.6806       0.9469             23.0
ensemble_erm_ermpp          felius_2024 0.8581 0.1394             0.7676       0.7353       0.8000              9.0
ensemble_erm_ermpp sint_maartenskliniek 0.8770 0.1526             0.8350       0.7700       0.9000              4.6
ensemble_erm_ermpp         voisard_2025 0.9027 0.1387             0.8357       0.7694       0.9020             16.6
               erm          felius_2024 0.8552 0.1648             0.7594       0.7529       0.7659              8.4
               erm sint_maartenskliniek 0.8650 0.1534             0.8000       0.7600       0.8400              4.8
               erm         voisard_2025 0.9008 0.1810             0.7908       0.6306       0.9510             26.6
       ermpp_style          felius_2024 0.8531 0.1274             0.7615       0.6765       0.8465             11.0
       ermpp_style sint_maartenskliniek 0.8410 0.1723             0.7950       0.7100       0.8800              5.8
       ermpp_style         voisard_2025 0.8862 0.1326             0.8132       0.8306       0.7959             12.2
{
  "selected_method": "ensemble_all",
  "candidate_decisions": {
    "coral": {
      "accepted": false,
      "noninferior": false,
      "material_gain": true,
      "worst_source_deltas": {
        "balanced_accuracy_delta": -0.020953032375740976,
        "specificity_delta": 0.09444444444444444,
        "sensitivity_delta": -0.07131782945736431,
        "auroc_delta": -0.0020519835841315004,
        "mean_brier_delta": -0.011782791520719038
      },
      "paired_bootstrap": {
        "balanced_accuracy": {
          "mean_delta": 0.008382246955629799,
          "ci_low": -0.03144447423672311,
          "ci_high": 0.05277676277229233
        },
        "specificity": {
          "mean_delta": 0.057952069716775606,
          "ci_low": -0.024968137254901945,
          "ci_high": 0.15223338779956427
        },
        "sensitivity": {
          "mean_delta": -0.041187575805516005,
          "ci_low": -0.07769255919422034,
          "ci_high": -0.008870959236407749
        },
        "auroc": {
          "mean_delta": 0.01780580139032357,
          "ci_low": 0.0004695952541222963,
          "ci_high": 0.038248064807318294
        },
        "brier": {
          "mean_delta": -0.011782791520719038,
          "ci_low": -0.047841077140736855,
          "ci_high": 0.022202851824386312
        }
      }
    },
    "ensemble_all": {
      "accepted": true,
      "noninferior": true,
      "material_gain": true,
      "worst_source_deltas": {
        "balanced_accuracy_delta": 0.0043319653442772665,
        "specificity_delta": 0.12777777777777788,
        "sensitivity_delta": -0.0031007751937983663,
        "auroc_delta": 0.0036023711810304615,
        "mean_brier_delta": -0.023897459825193423
      },
      "paired_bootstrap": {
        "balanced_accuracy": {
          "mean_delta": 0.030631441206973763,
          "ci_low": 0.0038244317752941003,
          "ci_high": 0.0636349333661113
        },
        "specificity": {
          "mean_delta": 0.05984749455337693,
          "ci_low": -0.001373366013071875,
          "ci_high": 0.13241013071895424
        },
        "sensitivity": {
          "mean_delta": 0.0014153878605705828,
          "ci_low": -0.022527052681537735,
          "ci_high": 0.02737333227864789
        },
        "auroc": {
          "mean_delta": 0.01454546159549092,
          "ci_low": 0.0011223471817667684,
          "ci_high": 0.03181049326707426
        },
        "brier": {
          "mean_delta": -0.02389745982519341,
          "ci_low": -0.04929244304067616,
          "ci_high": -0.0017727364487038803
        }
      }
    },
    "ensemble_erm_coral": {
      "accepted": false,
      "noninferior": false,
      "material_gain": true,
      "worst_source_deltas": {
        "balanced_accuracy_delta": -0.013497492020063895,
        "specificity_delta": 0.050000000000000044,
        "sensitivity_delta": -0.03875968992248058,
        "auroc_delta": 0.0003647970816232915,
        "mean_brier_delta": -0.012530645750881392
      },
      "paired_bootstrap": {
        "balanced_accuracy": {
          "mean_delta": 0.011487230551135178,
          "ci_low": -0.012451507605626223,
          "ci_high": 0.04053627200234094
        },
        "specificity": {
          "mean_delta": 0.03725490196078432,
          "ci_low": -0.006821895424836596,
          "ci_high": 0.09181018518518516
        },
        "sensitivity": {
          "mean_delta": -0.014280440858513942,
          "ci_low": -0.035799451563571165,
          "ci_high": 0.0025839793281653717
        },
        "auroc": {
          "mean_delta": 0.015922808399845743,
          "ci_low": 0.0032453712234247873,
          "ci_high": 0.032194750923625295
        },
        "brier": {
          "mean_delta": -0.01253064575088139,
          "ci_low": -0.03409820726317838,
          "ci_high": 0.00639550716309547
        }
      }
    },
    "ensemble_erm_ermpp": {
      "accepted": true,
      "noninferior": true,
      "material_gain": true,
      "worst_source_deltas": {
        "balanced_accuracy_delta": 0.008230734154126784,
        "specificity_delta": 0.10473856209150334,
        "sensitivity_delta": 0.03410852713178303,
        "auroc_delta": 0.002918376652986665,
        "mean_brier_delta": -0.022830354389733326
      },
      "paired_bootstrap": {
        "balanced_accuracy": {
          "mean_delta": 0.029395127560067954,
          "ci_low": 0.002891208356727711,
          "ci_high": 0.059565998750921556
        },
        "specificity": {
          "mean_delta": 0.04374727668845317,
          "ci_low": -0.02103540305010891,
          "ci_high": 0.11741993464052287
        },
        "sensitivity": {
          "mean_delta": 0.015042978431682756,
          "ci_low": -0.01608186995728524,
          "ci_high": 0.04649899804883191
        },
        "auroc": {
          "mean_delta": 0.005596374984102171,
          "ci_low": -0.00492121406702219,
          "ci_high": 0.018406734063134284
        },
        "brier": {
          "mean_delta": -0.022830354389733316,
          "ci_low": -0.045264587485367845,
          "ci_high": -0.00287109876831574
        }
      }
    },
    "ermpp_style": {
      "accepted": false,
      "noninferior": false,
      "material_gain": true,
      "worst_source_deltas": {
        "balanced_accuracy_delta": 0.002074783401732727,
        "specificity_delta": 0.04591503267973862,
        "sensitivity_delta": 0.030026894478721755,
        "auroc_delta": -0.014221158230734221,
        "mean_brier_delta": -0.02229387596566909
      },
      "paired_bootstrap": {
        "balanced_accuracy": {
          "mean_delta": 0.0065079209978565165,
          "ci_low": -0.029736093726896427,
          "ci_high": 0.043496173792514414
        },
        "specificity": {
          "mean_delta": 0.024509803921568638,
          "ci_low": -0.08943654684095861,
          "ci_high": 0.14454330065359478
        },
        "sensitivity": {
          "mean_delta": -0.011493961925855618,
          "ci_low": -0.08081218689025998,
          "ci_high": 0.057285239677266224
        },
        "auroc": {
          "mean_delta": -0.013570781284089868,
          "ci_low": -0.03679728560674917,
          "ci_high": 0.010024891765491754
        },
        "brier": {
          "mean_delta": -0.022293875965669067,
          "ci_low": -0.05712657006266019,
          "ci_high": 0.011200823131376209
        }
      }
    }
  },
  "selection_scope": "development-only repeated leave-one-source-out",
  "frozen_cohorts_loaded": false,
  "config": {
    "seeds": [
      42,
      137,
      202,
      314,
      515
    ],
    "tuning_seed": 20260903,
    "checkpoints": [
      4,
      8,
      12,
      16
    ],
    "per_source_batch": 64,
    "learning_rate": 0.001,
    "erm_weight_decay": 0.0001,
    "ermpp_weight_decay": 0.0005,
    "coral_weight": 1.0,
    "linear_steps": 500,
    "sma_start_step": 600,
    "validation_fraction": 0.2,
    "representation": "lower_back_acceleration"
  },
  "development_participants": 314,
  "development_windows": 22506,
  "sources": [
    "felius_2024",
    "sint_maartenskliniek",
    "voisard_2025"
  ],
  "input_sha256": {
    "primary": "71527c4d20ed50379b10649da08df0f8a0e271cb910b56a57d481a0587d5ee4a",
    "sint": "14c1e024a951c07f94f3e1bd94ec256a3efa8e001658dcd87c3c6b22df45d9c6"
  }
}

In [3]:
display(lower_back['tuning'].sort_values(['held_out_source', 'method', 'epoch']))
display(lower_back['summary'].sort_values(['method', 'held_out_source']).round(4))
print(json.dumps(lower_back['decision'], indent=2))

,held_out_source,method,epoch,worst_balanced_accuracy,worst_specificity,worst_sensitivity,worst_auroc,mean_brier,representation
4,felius_2024,coral,4,0.807143,0.714286,0.900000,0.914286,0.092514,lower_back_acceleration
5,felius_2024,coral,8,0.764286,0.928571,0.600000,0.921429,0.063590,lower_back_acceleration
6,felius_2024,coral,12,0.778571,0.857143,0.700000,0.942857,0.058107,lower_back_acceleration
7,felius_2024,coral,16,0.814286,0.928571,0.700000,0.950000,0.063386,lower_back_acceleration
0,felius_2024,erm,4,0.728571,0.857143,0.600000,0.921429,0.066963,lower_back_acceleration
1,felius_2024,erm,8,0.764286,0.928571,0.600000,0.935714,0.062068,lower_back_acceleration
2,felius_2024,erm,12,0.878571,0.857143,0.900000,0.928571,0.058706,lower_back_acceleration
3,felius_2024,erm,16,0.850000,1.000000,0.700000,0.950000,0.051737,lower_back_acceleration
8,felius_2024,ermpp_style,4,0.771429,0.642857,0.900000,0.892857,0.151908,lower_back_acceleration
9,felius_2024,ermpp_style,8,0.771429,0.642857,0.900000,0.900000,0.132253,lower_back_acceleration
10,felius_2024,ermpp_style,12,0.842857,0.785714,0.900000,0.857143,0.124838,lower_back_acceleration
11,felius_2024,ermpp_style,16,0.807143,0.714286,0.900000,0.907143,0.114238,lower_back_acceleration
16,sint_maartenskliniek,coral,4,0.778571,0.857143,0.700000,0.871429,0.111920,lower_back_acceleration
17,sint_maartenskliniek,coral,8,0.778571,0.857143,0.700000,0.907143,0.103144,lower_back_acceleration
18,sint_maartenskliniek,coral,12,0.800000,1.000000,0.600000,0.864286,0.139823,lower_back_acceleration
19,sint_maartenskliniek,coral,16,0.842857,0.785714,0.900000,0.921429,0.096674,lower_back_acceleration
12,sint_maartenskliniek,erm,4,0.778571,0.857143,0.700000,0.871429,0.124483,lower_back_acceleration
13,sint_maartenskliniek,erm,8,0.878571,0.857143,0.900000,0.921429,0.088544,lower_back_acceleration
14,sint_maartenskliniek,erm,12,0.778571,0.857143,0.700000,0.871429,0.130788,lower_back_acceleration
15,sint_maartenskliniek,erm,16,0.828571,0.857143,0.800000,0.917582,0.095873,lower_back_acceleration
20,sint_maartenskliniek,ermpp_style,4,0.671429,0.642857,0.700000,0.750000,0.170758,lower_back_acceleration
21,sint_maartenskliniek,ermpp_style,8,0.828571,0.857143,0.800000,0.885714,0.101053,lower_back_acceleration
22,sint_maartenskliniek,ermpp_style,12,0.785714,0.571429,1.000000,0.921429,0.097743,lower_back_acceleration
23,sint_maartenskliniek,ermpp_style,16,0.642857,0.285714,1.000000,0.921429,0.156796,lower_back_acceleration
28,voisard_2025,coral,4,0.928571,0.857143,1.000000,0.950549,0.058469,lower_back_acceleration
29,voisard_2025,coral,8,0.870879,0.857143,0.884615,0.928571,0.052107,lower_back_acceleration
30,voisard_2025,coral,12,0.875000,0.750000,0.961538,0.862637,0.080514,lower_back_acceleration
31,voisard_2025,coral,16,0.818681,0.714286,0.923077,0.923077,0.059014,lower_back_acceleration
24,voisard_2025,erm,4,0.928571,0.857143,1.000000,0.956044,0.064338,lower_back_acceleration
25,voisard_2025,erm,8,0.890110,0.857143,0.923077,0.890110,0.055486,lower_back_acceleration
26,voisard_2025,erm,12,0.857143,0.714286,1.000000,0.824176,0.129494,lower_back_acceleration
27,voisard_2025,erm,16,0.870879,0.857143,0.884615,0.939560,0.062495,lower_back_acceleration
32,voisard_2025,ermpp_style,4,0.903846,1.000000,0.807692,0.989011,0.097977,lower_back_acceleration
33,voisard_2025,ermpp_style,8,0.909341,0.857143,0.961538,0.978022,0.051561,lower_back_acceleration
34,voisard_2025,ermpp_style,12,0.870879,0.857143,0.884615,0.967033,0.051236,lower_back_acceleration
35,voisard_2025,ermpp_style,16,0.870879,0.857143,0.884615,0.972527,0.050551,lower_back_acceleration

,method,held_out_source,auroc,brier,balanced_accuracy,specificity,sensitivity,false_positives
0,coral,felius_2024,0.8532,0.2047,0.7385,0.7824,0.6946,7.4
1,coral,sint_maartenskliniek,0.8970,0.1271,0.8050,0.8100,0.8000,3.8
2,coral,voisard_2025,0.9243,0.1321,0.8319,0.7250,0.9388,19.8
3,ensemble_all,felius_2024,0.8588,0.1551,0.7637,0.7647,0.7628,8.0
4,ensemble_all,sint_maartenskliniek,0.8950,0.1387,0.8400,0.8000,0.8800,4.0
5,ensemble_all,voisard_2025,0.9108,0.1338,0.8384,0.7583,0.9184,17.4
6,ensemble_erm_coral,felius_2024,0.8556,0.1805,0.7459,0.7647,0.7271,8.0
7,ensemble_erm_coral,sint_maartenskliniek,0.8950,0.1317,0.8250,0.8100,0.8400,3.8
8,ensemble_erm_coral,voisard_2025,0.9182,0.1495,0.8137,0.6806,0.9469,23.0
9,ensemble_erm_ermpp,felius_2024,0.8581,0.1394,0.7676,0.7353,0.8000,9.0
10,ensemble_erm_ermpp,sint_maartenskliniek,0.8770,0.1526,0.8350,0.7700,0.9000,4.6
11,ensemble_erm_ermpp,voisard_2025,0.9027,0.1387,0.8357,0.7694,0.9020,16.6
12,erm,felius_2024,0.8552,0.1648,0.7594,0.7529,0.7659,8.4
13,erm,sint_maartenskliniek,0.8650,0.1534,0.8000,0.7600,0.8400,4.8
14,erm,voisard_2025,0.9008,0.1810,0.7908,0.6306,0.9510,26.6
15,ermpp_style,felius_2024,0.8531,0.1274,0.7615,0.6765,0.8465,11.0
16,ermpp_style,sint_maartenskliniek,0.8410,0.1723,0.7950,0.7100,0.8800,5.8
17,ermpp_style,voisard_2025,0.8862,0.1326,0.8132,0.8306,0.7959,12.2

{
  "selected_method": "ensemble_all",
  "candidate_decisions": {
    "coral": {
      "accepted": false,
      "noninferior": false,
      "material_gain": true,
      "worst_source_deltas": {
        "balanced_accuracy_delta": -0.020953032375740976,
        "specificity_delta": 0.09444444444444444,
        "sensitivity_delta": -0.07131782945736431,
        "auroc_delta": -0.0020519835841315004,
        "mean_brier_delta": -0.011782791520719038
      },
      "paired_bootstrap": {
        "balanced_accuracy": {
          "mean_delta": 0.008382246955629799,
          "ci_low": -0.03144447423672311,
          "ci_high": 0.05277676277229233
        },
        "specificity": {
          "mean_delta": 0.057952069716775606,
          "ci_low": -0.024968137254901945,
          "ci_high": 0.15223338779956427
        },
        "sensitivity": {
          "mean_delta": -0.041187575805516005,
          "ci_low": -0.07769255919422034,
          "ci_high": -0.008870959236407749
        },
        "auroc": {
          "mean_delta": 0.01780580139032357,
          "ci_low": 0.0004695952541222963,
          "ci_high": 0.038248064807318294
        },
        "brier": {
          "mean_delta": -0.011782791520719038,
          "ci_low": -0.047841077140736855,
          "ci_high": 0.022202851824386312
        }
      }
    },
    "ensemble_all": {
      "accepted": true,
      "noninferior": true,
      "material_gain": true,
      "worst_source_deltas": {
        "balanced_accuracy_delta": 0.0043319653442772665,
        "specificity_delta": 0.12777777777777788,
        "sensitivity_delta": -0.0031007751937983663,
        "auroc_delta": 0.0036023711810304615,
        "mean_brier_delta": -0.023897459825193423
      },
      "paired_bootstrap": {
        "balanced_accuracy": {
          "mean_delta": 0.030631441206973763,
          "ci_low": 0.0038244317752941003,
          "ci_high": 0.0636349333661113
        },
        "specificity": {
          "mean_delta": 0.05984749455337693,
          "ci_low": -0.001373366013071875,
          "ci_high": 0.13241013071895424
        },
        "sensitivity": {
          "mean_delta": 0.0014153878605705828,
          "ci_low": -0.022527052681537735,
          "ci_high": 0.02737333227864789
        },
        "auroc": {
          "mean_delta": 0.01454546159549092,
          "ci_low": 0.0011223471817667684,
          "ci_high": 0.03181049326707426
        },
        "brier": {
          "mean_delta": -0.02389745982519341,
          "ci_low": -0.04929244304067616,
          "ci_high": -0.0017727364487038803
        }
      }
    },
    "ensemble_erm_coral": {
      "accepted": false,
      "noninferior": false,
      "material_gain": true,
      "worst_source_deltas": {
        "balanced_accuracy_delta": -0.013497492020063895,
        "specificity_delta": 0.050000000000000044,
        "sensitivity_delta": -0.03875968992248058,
        "auroc_delta": 0.0003647970816232915,
        "mean_brier_delta": -0.012530645750881392
      },
      "paired_bootstrap": {
        "balanced_accuracy": {
          "mean_delta": 0.011487230551135178,
          "ci_low": -0.012451507605626223,
          "ci_high": 0.04053627200234094
        },
        "specificity": {
          "mean_delta": 0.03725490196078432,
          "ci_low": -0.006821895424836596,
          "ci_high": 0.09181018518518516
        },
        "sensitivity": {
          "mean_delta": -0.014280440858513942,
          "ci_low": -0.035799451563571165,
          "ci_high": 0.0025839793281653717
        },
        "auroc": {
          "mean_delta": 0.015922808399845743,
          "ci_low": 0.0032453712234247873,
          "ci_high": 0.032194750923625295
        },
        "brier": {
          "mean_delta": -0.01253064575088139,
          "ci_low": -0.03409820726317838,
          "ci_high": 0.00639550716309547
        }
      }
    },
    "ensemble_erm_ermpp": {
      "accepted": true,
      "noninferior": true,
      "material_gain": true,
      "worst_source_deltas": {
        "balanced_accuracy_delta": 0.008230734154126784,
        "specificity_delta": 0.10473856209150334,
        "sensitivity_delta": 0.03410852713178303,
        "auroc_delta": 0.002918376652986665,
        "mean_brier_delta": -0.022830354389733326
      },
      "paired_bootstrap": {
        "balanced_accuracy": {
          "mean_delta": 0.029395127560067954,
          "ci_low": 0.002891208356727711,
          "ci_high": 0.059565998750921556
        },
        "specificity": {
          "mean_delta": 0.04374727668845317,
          "ci_low": -0.02103540305010891,
          "ci_high": 0.11741993464052287
        },
        "sensitivity": {
          "mean_delta": 0.015042978431682756,
          "ci_low": -0.01608186995728524,
          "ci_high": 0.04649899804883191
        },
        "auroc": {
          "mean_delta": 0.005596374984102171,
          "ci_low": -0.00492121406702219,
          "ci_high": 0.018406734063134284
        },
        "brier": {
          "mean_delta": -0.022830354389733316,
          "ci_low": -0.045264587485367845,
          "ci_high": -0.00287109876831574
        }
      }
    },
    "ermpp_style": {
      "accepted": false,
      "noninferior": false,
      "material_gain": true,
      "worst_source_deltas": {
        "balanced_accuracy_delta": 0.002074783401732727,
        "specificity_delta": 0.04591503267973862,
        "sensitivity_delta": 0.030026894478721755,
        "auroc_delta": -0.014221158230734221,
        "mean_brier_delta": -0.02229387596566909
      },
      "paired_bootstrap": {
        "balanced_accuracy": {
          "mean_delta": 0.0065079209978565165,
          "ci_low": -0.029736093726896427,
          "ci_high": 0.043496173792514414
        },
        "specificity": {
          "mean_delta": 0.024509803921568638,
          "ci_low": -0.08943654684095861,
          "ci_high": 0.14454330065359478
        },
        "sensitivity": {
          "mean_delta": -0.011493961925855618,
          "ci_low": -0.08081218689025998,
          "ci_high": 0.057285239677266224
        },
        "auroc": {
          "mean_delta": -0.013570781284089868,
          "ci_low": -0.03679728560674917,
          "ci_high": 0.010024891765491754
        },
        "brier": {
          "mean_delta": -0.022293875965669067,
          "ci_low": -0.05712657006266019,
          "ci_high": 0.011200823131376209
        }
      }
    }
  },
  "selection_scope": "development-only repeated leave-one-source-out",
  "frozen_cohorts_loaded": false,
  "config": {
    "seeds": [
      42,
      137,
      202,
      314,
      515
    ],
    "tuning_seed": 20260903,
    "checkpoints": [
      4,
      8,
      12,
      16
    ],
    "per_source_batch": 64,
    "learning_rate": 0.001,
    "erm_weight_decay": 0.0001,
    "ermpp_weight_decay": 0.0005,
    "coral_weight": 1.0,
    "linear_steps": 500,
    "sma_start_step": 600,
    "validation_fraction": 0.2,
    "representation": "lower_back_acceleration"
  },
  "development_participants": 314,
  "development_windows": 22506,
  "sources": [
    "felius_2024",
    "sint_maartenskliniek",
    "voisard_2025"
  ],
  "input_sha256": {
    "primary": "71527c4d20ed50379b10649da08df0f8a0e271cb910b56a57d481a0587d5ee4a",
    "sint": "14c1e024a951c07f94f3e1bd94ec256a3efa8e001658dcd87c3c6b22df45d9c6"
  }
}

In [4]:
selected = lower_back['decision']['selected_method']
if selected != 'erm':
    print(f'{selected} passed the lower-back gate; starting the predeclared three-channel confirmation.')
    three_channel = run(ROOT, BenchmarkConfig(representation='three_channel_acceleration'))
    display(three_channel['summary'].sort_values(['method', 'held_out_source']).round(4))
    print(json.dumps(three_channel['decision'], indent=2))
else:
    three_channel = None
    print('No candidate passed the lower-back gate. Three-channel confirmation correctly skipped.')

ensemble_all passed the lower-back gate; starting the predeclared three-channel confirmation.
Device: cuda | NVIDIA GeForce RTX 5060 Laptop GPU
Representation: three_channel_acceleration | channels=[0, 1, 2]
source                label
felius_2024           healthy     34
                      stroke     129
sint_maartenskliniek  healthy     20
                      stroke      10
voisard_2025          healthy     72
                      stroke      49
Name: participants, dtype: int64

C:\Users\frank\Documents\MR-ICT Review Paper\src\models\evidence_gated_domain_generalization.py:410: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  validation_history = history_frame.loc[history_frame.get("validation", False).fillna(False)].copy()

Tuned felius_2024 erm: 16 epochs

C:\Users\frank\Documents\MR-ICT Review Paper\src\models\evidence_gated_domain_generalization.py:410: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  validation_history = history_frame.loc[history_frame.get("validation", False).fillna(False)].copy()

Tuned felius_2024 coral: 8 epochs

C:\Users\frank\Documents\MR-ICT Review Paper\src\models\evidence_gated_domain_generalization.py:410: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  validation_history = history_frame.loc[history_frame.get("validation", False).fillna(False)].copy()

Tuned felius_2024 ermpp_style: 16 epochs

C:\Users\frank\Documents\MR-ICT Review Paper\src\models\evidence_gated_domain_generalization.py:410: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  validation_history = history_frame.loc[history_frame.get("validation", False).fillna(False)].copy()

Tuned sint_maartenskliniek erm: 12 epochs

C:\Users\frank\Documents\MR-ICT Review Paper\src\models\evidence_gated_domain_generalization.py:410: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  validation_history = history_frame.loc[history_frame.get("validation", False).fillna(False)].copy()

Tuned sint_maartenskliniek coral: 12 epochs

C:\Users\frank\Documents\MR-ICT Review Paper\src\models\evidence_gated_domain_generalization.py:410: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  validation_history = history_frame.loc[history_frame.get("validation", False).fillna(False)].copy()

Tuned sint_maartenskliniek ermpp_style: 16 epochs

C:\Users\frank\Documents\MR-ICT Review Paper\src\models\evidence_gated_domain_generalization.py:410: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  validation_history = history_frame.loc[history_frame.get("validation", False).fillna(False)].copy()

Tuned voisard_2025 erm: 12 epochs

C:\Users\frank\Documents\MR-ICT Review Paper\src\models\evidence_gated_domain_generalization.py:410: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  validation_history = history_frame.loc[history_frame.get("validation", False).fillna(False)].copy()

Tuned voisard_2025 coral: 8 epochs

C:\Users\frank\Documents\MR-ICT Review Paper\src\models\evidence_gated_domain_generalization.py:410: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  validation_history = history_frame.loc[history_frame.get("validation", False).fillna(False)].copy()

Tuned voisard_2025 ermpp_style: 16 epochs

Complete felius_2024 seed=42 method=erm

Complete felius_2024 seed=42 method=coral

Complete felius_2024 seed=42 method=ermpp_style

Complete felius_2024 seed=137 method=erm

Complete felius_2024 seed=137 method=coral

Complete felius_2024 seed=137 method=ermpp_style

Complete felius_2024 seed=202 method=erm

Complete felius_2024 seed=202 method=coral

Complete felius_2024 seed=202 method=ermpp_style

Complete felius_2024 seed=314 method=erm

Complete felius_2024 seed=314 method=coral

Complete felius_2024 seed=314 method=ermpp_style

Complete felius_2024 seed=515 method=erm

Complete felius_2024 seed=515 method=coral

Complete felius_2024 seed=515 method=ermpp_style

Complete sint_maartenskliniek seed=42 method=erm

Complete sint_maartenskliniek seed=42 method=coral

Complete sint_maartenskliniek seed=42 method=ermpp_style

Complete sint_maartenskliniek seed=137 method=erm

Complete sint_maartenskliniek seed=137 method=coral

Complete sint_maartenskliniek seed=137 method=ermpp_style

Complete sint_maartenskliniek seed=202 method=erm

Complete sint_maartenskliniek seed=202 method=coral

Complete sint_maartenskliniek seed=202 method=ermpp_style

Complete sint_maartenskliniek seed=314 method=erm

Complete sint_maartenskliniek seed=314 method=coral

Complete sint_maartenskliniek seed=314 method=ermpp_style

Complete sint_maartenskliniek seed=515 method=erm

Complete sint_maartenskliniek seed=515 method=coral

Complete sint_maartenskliniek seed=515 method=ermpp_style

Complete voisard_2025 seed=42 method=erm

Complete voisard_2025 seed=42 method=coral

Complete voisard_2025 seed=42 method=ermpp_style

Complete voisard_2025 seed=137 method=erm

Complete voisard_2025 seed=137 method=coral

Complete voisard_2025 seed=137 method=ermpp_style

Complete voisard_2025 seed=202 method=erm

Complete voisard_2025 seed=202 method=coral

Complete voisard_2025 seed=202 method=ermpp_style

Complete voisard_2025 seed=314 method=erm

Complete voisard_2025 seed=314 method=coral

Complete voisard_2025 seed=314 method=ermpp_style

Complete voisard_2025 seed=515 method=erm

Complete voisard_2025 seed=515 method=coral

Complete voisard_2025 seed=515 method=ermpp_style

            method      held_out_source  auroc  brier  balanced_accuracy  specificity  sensitivity  false_positives
             coral          felius_2024 0.8808 0.2562             0.7299       0.8706       0.5891              4.4
             coral sint_maartenskliniek 0.8690 0.1219             0.8100       0.9600       0.6600              0.8
             coral         voisard_2025 0.9420 0.1228             0.8362       0.7500       0.9224             18.0
      ensemble_all          felius_2024 0.8870 0.2222             0.7493       0.8412       0.6574              5.4
      ensemble_all sint_maartenskliniek 0.8830 0.1091             0.8100       0.9200       0.7000              1.6
      ensemble_all         voisard_2025 0.9361 0.1237             0.8397       0.7611       0.9184             17.2
ensemble_erm_coral          felius_2024 0.8891 0.2409             0.7519       0.8882       0.6155              3.8
ensemble_erm_coral sint_maartenskliniek 0.8710 0.1202             0.8150       0.9500       0.6800              1.0
ensemble_erm_coral         voisard_2025 0.9405 0.1315             0.8415       0.7361       0.9469             19.0
ensemble_erm_ermpp          felius_2024 0.8879 0.2109             0.7662       0.8471       0.6853              5.2
ensemble_erm_ermpp sint_maartenskliniek 0.8890 0.1047             0.8100       0.9000       0.7200              2.0
ensemble_erm_ermpp         voisard_2025 0.9307 0.1265             0.8405       0.7667       0.9143             16.8
               erm          felius_2024 0.8918 0.2340             0.7610       0.8941       0.6279              3.6
               erm sint_maartenskliniek 0.8700 0.1198             0.8100       0.9400       0.6800              1.2
               erm         voisard_2025 0.9300 0.1487             0.8166       0.6944       0.9388             22.0
       ermpp_style          felius_2024 0.8810 0.1960             0.7676       0.8235       0.7116              6.0
       ermpp_style sint_maartenskliniek 0.9080 0.0962             0.8300       0.8800       0.7800              2.4
       ermpp_style         voisard_2025 0.9211 0.1194             0.8374       0.7972       0.8776             14.6
{
  "selected_method": "ensemble_erm_ermpp",
  "candidate_decisions": {
    "coral": {
      "accepted": false,
      "noninferior": false,
      "material_gain": false,
      "worst_source_deltas": {
        "balanced_accuracy_delta": -0.031144550843593355,
        "specificity_delta": 0.05555555555555558,
        "sensitivity_delta": -0.03875968992248069,
        "auroc_delta": -0.0010000000000000009,
        "mean_brier_delta": -0.0005505096165737688
      },
      "paired_bootstrap": {
        "balanced_accuracy": {
          "mean_delta": -0.003843346123979326,
          "ci_low": -0.029131076849344434,
          "ci_high": 0.020840084806532412
        },
        "specificity": {
          "mean_delta": 0.017342047930283214,
          "ci_low": -0.01695261437908497,
          "ci_high": 0.06266966230936817
        },
        "sensitivity": {
          "mean_delta": -0.025028740178241846,
          "ci_low": -0.07108790803142963,
          "ci_high": 0.012328719084533028
        },
        "auroc": {
          "mean_delta": -4.344993811478866e-05,
          "ci_low": -0.008289436730764703,
          "ci_high": 0.009495257172636511
        },
        "brier": {
          "mean_delta": -0.0005505096165737984,
          "ci_low": -0.022176521643683583,
          "ci_high": 0.024183016886855587
        }
      }
    },
    "ensemble_all": {
      "accepted": false,
      "noninferior": false,
      "material_gain": true,
      "worst_source_deltas": {
        "balanced_accuracy_delta": -0.011741906064751562,
        "specificity_delta": 0.06666666666666665,
        "sensitivity_delta": 0.029457364341085257,
        "auroc_delta": 0.0129999999999999,
        "mean_brier_delta": -0.01583614045546597
      },
      "paired_bootstrap": {
        "balanced_accuracy": {
          "mean_delta": 0.0037957818786429195,
          "ci_low": -0.011642611566590487,
          "ci_high": 0.022702382244887603
        },
        "specificity": {
          "mean_delta": -0.002091503267973864,
          "ci_low": -0.03481672113289762,
          "ci_high": 0.04059912854030501
        },
        "sensitivity": {
          "mean_delta": 0.00968306702525971,
          "ci_low": -0.010504666983072309,
          "ci_high": 0.032214760322733724
        },
        "auroc": {
          "mean_delta": 0.004774465858694891,
          "ci_low": -0.0016905184812943156,
          "ci_high": 0.011884816433033157
        },
        "brier": {
          "mean_delta": -0.015836140455466,
          "ci_low": -0.029976082635196456,
          "ci_high": -0.004486158215006366
        }
      }
    },
    "ensemble_erm_coral": {
      "accepted": false,
      "noninferior": false,
      "material_gain": true,
      "worst_source_deltas": {
        "balanced_accuracy_delta": -0.00914272685818518,
        "specificity_delta": 0.04166666666666663,
        "sensitivity_delta": -0.012403100775193798,
        "auroc_delta": 0.0010000000000000009,
        "mean_brier_delta": -0.003331432499073861
      },
      "paired_bootstrap": {
        "balanced_accuracy": {
          "mean_delta": 0.006924079709403142,
          "ci_low": -0.007648195195390814,
          "ci_high": 0.022046353942093627
        },
        "specificity": {
          "mean_delta": 0.015261437908496722,
          "ci_low": -0.004814814814814835,
          "ci_high": 0.039335511982570806
        },
        "sensitivity": {
          "mean_delta": -0.0014132784896904542,
          "ci_low": -0.022496440436639786,
          "ci_high": 0.016981753941886824
        },
        "auroc": {
          "mean_delta": 0.0028982869633641458,
          "ci_low": -0.001644889790541546,
          "ci_high": 0.008410791603463084
        },
        "brier": {
          "mean_delta": -0.0033314324990738934,
          "ci_low": -0.014862734245139352,
          "ci_high": 0.007650344693225531
        }
      }
    },
    "ensemble_erm_ermpp": {
      "accepted": true,
      "noninferior": true,
      "material_gain": true,
      "worst_source_deltas": {
        "balanced_accuracy_delta": 0.005152758777929645,
        "specificity_delta": 0.0722222222222223,
        "sensitivity_delta": 0.05736434108527133,
        "auroc_delta": 0.017870497036023614,
        "mean_brier_delta": -0.020134397521883146
      },
      "paired_bootstrap": {
        "balanced_accuracy": {
          "mean_delta": 0.009672990643285743,
          "ci_low": -0.0068011311759845995,
          "ci_high": 0.02884873006049966
        },
        "specificity": {
          "mean_delta": -0.004945533769063186,
          "ci_low": -0.04019689542483661,
          "ci_high": 0.03919417211328976
        },
        "sensitivity": {
          "mean_delta": 0.024291515055634656,
          "ci_low": -0.0009597637504614215,
          "ci_high": 0.05109426251120602
        },
        "auroc": {
          "mean_delta": 0.00523400471299631,
          "ci_low": -0.002233312549826111,
          "ci_high": 0.013942060545148295
        },
        "brier": {
          "mean_delta": -0.02013439752188319,
          "ci_low": -0.0328693449760506,
          "ci_high": -0.010067258079380598
        }
      }
    },
    "ermpp_style": {
      "accepted": false,
      "noninferior": false,
      "material_gain": true,
      "worst_source_deltas": {
        "balanced_accuracy_delta": 0.006566347469220246,
        "specificity_delta": 0.10277777777777786,
        "sensitivity_delta": 0.08372093023255811,
        "auroc_delta": 0.01103055175558576,
        "mean_brier_delta": -0.03028326377651705
      },
      "paired_bootstrap": {
        "balanced_accuracy": {
          "mean_delta": 0.015780997153383332,
          "ci_low": -0.002072459280869953,
          "ci_high": 0.035438322421992054
        },
        "specificity": {
          "mean_delta": -0.009270152505446634,
          "ci_low": -0.05812826797385623,
          "ci_high": 0.05419417211328975
        },
        "sensitivity": {
          "mean_delta": 0.04083214681221327,
          "ci_low": -0.005727231978062545,
          "ci_high": 0.08562118335706377
        },
        "auroc": {
          "mean_delta": 0.006112753111580557,
          "ci_low": -0.007952145147464644,
          "ci_high": 0.02149137652477012
        },
        "brier": {
          "mean_delta": -0.030283263776517112,
          "ci_low": -0.04914179803460391,
          "ci_high": -0.014467396537921886
        }
      }
    }
  },
  "selection_scope": "development-only repeated leave-one-source-out",
  "frozen_cohorts_loaded": false,
  "config": {
    "seeds": [
      42,
      137,
      202,
      314,
      515
    ],
    "tuning_seed": 20260903,
    "checkpoints": [
      4,
      8,
      12,
      16
    ],
    "per_source_batch": 64,
    "learning_rate": 0.001,
    "erm_weight_decay": 0.0001,
    "ermpp_weight_decay": 0.0005,
    "coral_weight": 1.0,
    "linear_steps": 500,
    "sma_start_step": 600,
    "validation_fraction": 0.2,
    "representation": "three_channel_acceleration"
  },
  "development_participants": 314,
  "development_windows": 22506,
  "sources": [
    "felius_2024",
    "sint_maartenskliniek",
    "voisard_2025"
  ],
  "input_sha256": {
    "primary": "71527c4d20ed50379b10649da08df0f8a0e271cb910b56a57d481a0587d5ee4a",
    "sint": "14c1e024a951c07f94f3e1bd94ec256a3efa8e001658dcd87c3c6b22df45d9c6"
  }
}

,method,held_out_source,auroc,brier,balanced_accuracy,specificity,sensitivity,false_positives
0,coral,felius_2024,0.8808,0.2562,0.7299,0.8706,0.5891,4.4
1,coral,sint_maartenskliniek,0.8690,0.1219,0.8100,0.9600,0.6600,0.8
2,coral,voisard_2025,0.9420,0.1228,0.8362,0.7500,0.9224,18.0
3,ensemble_all,felius_2024,0.8870,0.2222,0.7493,0.8412,0.6574,5.4
4,ensemble_all,sint_maartenskliniek,0.8830,0.1091,0.8100,0.9200,0.7000,1.6
5,ensemble_all,voisard_2025,0.9361,0.1237,0.8397,0.7611,0.9184,17.2
6,ensemble_erm_coral,felius_2024,0.8891,0.2409,0.7519,0.8882,0.6155,3.8
7,ensemble_erm_coral,sint_maartenskliniek,0.8710,0.1202,0.8150,0.9500,0.6800,1.0
8,ensemble_erm_coral,voisard_2025,0.9405,0.1315,0.8415,0.7361,0.9469,19.0
9,ensemble_erm_ermpp,felius_2024,0.8879,0.2109,0.7662,0.8471,0.6853,5.2
10,ensemble_erm_ermpp,sint_maartenskliniek,0.8890,0.1047,0.8100,0.9000,0.7200,2.0
11,ensemble_erm_ermpp,voisard_2025,0.9307,0.1265,0.8405,0.7667,0.9143,16.8
12,erm,felius_2024,0.8918,0.2340,0.7610,0.8941,0.6279,3.6
13,erm,sint_maartenskliniek,0.8700,0.1198,0.8100,0.9400,0.6800,1.2
14,erm,voisard_2025,0.9300,0.1487,0.8166,0.6944,0.9388,22.0
15,ermpp_style,felius_2024,0.8810,0.1960,0.7676,0.8235,0.7116,6.0
16,ermpp_style,sint_maartenskliniek,0.9080,0.0962,0.8300,0.8800,0.7800,2.4
17,ermpp_style,voisard_2025,0.9211,0.1194,0.8374,0.7972,0.8776,14.6

{
  "selected_method": "ensemble_erm_ermpp",
  "candidate_decisions": {
    "coral": {
      "accepted": false,
      "noninferior": false,
      "material_gain": false,
      "worst_source_deltas": {
        "balanced_accuracy_delta": -0.031144550843593355,
        "specificity_delta": 0.05555555555555558,
        "sensitivity_delta": -0.03875968992248069,
        "auroc_delta": -0.0010000000000000009,
        "mean_brier_delta": -0.0005505096165737688
      },
      "paired_bootstrap": {
        "balanced_accuracy": {
          "mean_delta": -0.003843346123979326,
          "ci_low": -0.029131076849344434,
          "ci_high": 0.020840084806532412
        },
        "specificity": {
          "mean_delta": 0.017342047930283214,
          "ci_low": -0.01695261437908497,
          "ci_high": 0.06266966230936817
        },
        "sensitivity": {
          "mean_delta": -0.025028740178241846,
          "ci_low": -0.07108790803142963,
          "ci_high": 0.012328719084533028
        },
        "auroc": {
          "mean_delta": -4.344993811478866e-05,
          "ci_low": -0.008289436730764703,
          "ci_high": 0.009495257172636511
        },
        "brier": {
          "mean_delta": -0.0005505096165737984,
          "ci_low": -0.022176521643683583,
          "ci_high": 0.024183016886855587
        }
      }
    },
    "ensemble_all": {
      "accepted": false,
      "noninferior": false,
      "material_gain": true,
      "worst_source_deltas": {
        "balanced_accuracy_delta": -0.011741906064751562,
        "specificity_delta": 0.06666666666666665,
        "sensitivity_delta": 0.029457364341085257,
        "auroc_delta": 0.0129999999999999,
        "mean_brier_delta": -0.01583614045546597
      },
      "paired_bootstrap": {
        "balanced_accuracy": {
          "mean_delta": 0.0037957818786429195,
          "ci_low": -0.011642611566590487,
          "ci_high": 0.022702382244887603
        },
        "specificity": {
          "mean_delta": -0.002091503267973864,
          "ci_low": -0.03481672113289762,
          "ci_high": 0.04059912854030501
        },
        "sensitivity": {
          "mean_delta": 0.00968306702525971,
          "ci_low": -0.010504666983072309,
          "ci_high": 0.032214760322733724
        },
        "auroc": {
          "mean_delta": 0.004774465858694891,
          "ci_low": -0.0016905184812943156,
          "ci_high": 0.011884816433033157
        },
        "brier": {
          "mean_delta": -0.015836140455466,
          "ci_low": -0.029976082635196456,
          "ci_high": -0.004486158215006366
        }
      }
    },
    "ensemble_erm_coral": {
      "accepted": false,
      "noninferior": false,
      "material_gain": true,
      "worst_source_deltas": {
        "balanced_accuracy_delta": -0.00914272685818518,
        "specificity_delta": 0.04166666666666663,
        "sensitivity_delta": -0.012403100775193798,
        "auroc_delta": 0.0010000000000000009,
        "mean_brier_delta": -0.003331432499073861
      },
      "paired_bootstrap": {
        "balanced_accuracy": {
          "mean_delta": 0.006924079709403142,
          "ci_low": -0.007648195195390814,
          "ci_high": 0.022046353942093627
        },
        "specificity": {
          "mean_delta": 0.015261437908496722,
          "ci_low": -0.004814814814814835,
          "ci_high": 0.039335511982570806
        },
        "sensitivity": {
          "mean_delta": -0.0014132784896904542,
          "ci_low": -0.022496440436639786,
          "ci_high": 0.016981753941886824
        },
        "auroc": {
          "mean_delta": 0.0028982869633641458,
          "ci_low": -0.001644889790541546,
          "ci_high": 0.008410791603463084
        },
        "brier": {
          "mean_delta": -0.0033314324990738934,
          "ci_low": -0.014862734245139352,
          "ci_high": 0.007650344693225531
        }
      }
    },
    "ensemble_erm_ermpp": {
      "accepted": true,
      "noninferior": true,
      "material_gain": true,
      "worst_source_deltas": {
        "balanced_accuracy_delta": 0.005152758777929645,
        "specificity_delta": 0.0722222222222223,
        "sensitivity_delta": 0.05736434108527133,
        "auroc_delta": 0.017870497036023614,
        "mean_brier_delta": -0.020134397521883146
      },
      "paired_bootstrap": {
        "balanced_accuracy": {
          "mean_delta": 0.009672990643285743,
          "ci_low": -0.0068011311759845995,
          "ci_high": 0.02884873006049966
        },
        "specificity": {
          "mean_delta": -0.004945533769063186,
          "ci_low": -0.04019689542483661,
          "ci_high": 0.03919417211328976
        },
        "sensitivity": {
          "mean_delta": 0.024291515055634656,
          "ci_low": -0.0009597637504614215,
          "ci_high": 0.05109426251120602
        },
        "auroc": {
          "mean_delta": 0.00523400471299631,
          "ci_low": -0.002233312549826111,
          "ci_high": 0.013942060545148295
        },
        "brier": {
          "mean_delta": -0.02013439752188319,
          "ci_low": -0.0328693449760506,
          "ci_high": -0.010067258079380598
        }
      }
    },
    "ermpp_style": {
      "accepted": false,
      "noninferior": false,
      "material_gain": true,
      "worst_source_deltas": {
        "balanced_accuracy_delta": 0.006566347469220246,
        "specificity_delta": 0.10277777777777786,
        "sensitivity_delta": 0.08372093023255811,
        "auroc_delta": 0.01103055175558576,
        "mean_brier_delta": -0.03028326377651705
      },
      "paired_bootstrap": {
        "balanced_accuracy": {
          "mean_delta": 0.015780997153383332,
          "ci_low": -0.002072459280869953,
          "ci_high": 0.035438322421992054
        },
        "specificity": {
          "mean_delta": -0.009270152505446634,
          "ci_low": -0.05812826797385623,
          "ci_high": 0.05419417211328975
        },
        "sensitivity": {
          "mean_delta": 0.04083214681221327,
          "ci_low": -0.005727231978062545,
          "ci_high": 0.08562118335706377
        },
        "auroc": {
          "mean_delta": 0.006112753111580557,
          "ci_low": -0.007952145147464644,
          "ci_high": 0.02149137652477012
        },
        "brier": {
          "mean_delta": -0.030283263776517112,
          "ci_low": -0.04914179803460391,
          "ci_high": -0.014467396537921886
        }
      }
    }
  },
  "selection_scope": "development-only repeated leave-one-source-out",
  "frozen_cohorts_loaded": false,
  "config": {
    "seeds": [
      42,
      137,
      202,
      314,
      515
    ],
    "tuning_seed": 20260903,
    "checkpoints": [
      4,
      8,
      12,
      16
    ],
    "per_source_batch": 64,
    "learning_rate": 0.001,
    "erm_weight_decay": 0.0001,
    "ermpp_weight_decay": 0.0005,
    "coral_weight": 1.0,
    "linear_steps": 500,
    "sma_start_step": 600,
    "validation_fraction": 0.2,
    "representation": "three_channel_acceleration"
  },
  "development_participants": 314,
  "development_windows": 22506,
  "sources": [
    "felius_2024",
    "sint_maartenskliniek",
    "voisard_2025"
  ],
  "input_sha256": {
    "primary": "71527c4d20ed50379b10649da08df0f8a0e271cb910b56a57d481a0587d5ee4a",
    "sint": "14c1e024a951c07f94f3e1bd94ec256a3efa8e001658dcd87c3c6b22df45d9c6"
  }
}

In [5]:
decision = lower_back['decision']
print('FINAL DEVELOPMENT DECISION')
print('Selected method:', decision['selected_method'])
print('Selection scope:', decision['selection_scope'])
print('Frozen cohorts loaded:', decision['frozen_cohorts_loaded'])
print('Interpretation: this is a development-domain robustness decision, not a claim of clinical readiness.')

FINAL DEVELOPMENT DECISION
Selected method: ensemble_all
Selection scope: development-only repeated leave-one-source-out
Frozen cohorts loaded: False
Interpretation: this is a development-domain robustness decision, not a claim of clinical readiness.